pool:
  name: laptop
  demands: maven

variables:
  mavenPOMFile: 'pom.xml'

steps:
- task: Maven@3
  displayName: 'Maven compile'
  inputs:
    mavenPomFile: '$(mavenPOMFile)'
    goals: compile

- task: Maven@3
  displayName: 'Maven package'
  inputs:
    mavenPomFile: '$(mavenPOMFile)'
    goals: package

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
